//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int prodId { get; set; }
        public string prodName { get; set; }
        public string prodDesc { get; set; }
        public string prodImage { get; set; }
    }
}
